### PR TITLE
Mouse wheel to maximize/unmaximize windows

### PR DESCRIPTION
**Pull request by linchangyi**
Maxmize/Unmaximize windows by mouse wheel up/down.

### CODE REVIEW

**Comment by psifidotos** [comment]
Sorry I find this out of scope

**Comment by linchangyi** [comment]
> Sorry I find this out of scope

Sorry,  my english is poor,  I dont understand  'out of scope'? Do you mean this feature is unnecessary?

**Comment by psifidotos** [comment]
Oh, it is a MR and is applied only for plasma panels... Let me think it more...

**Comment by linchangyi** [comment]
I used to be the user of plasma-active-window-control, and it has this feature which  I found very useful for me.

**Pull request merged**
